### PR TITLE
Added overview to Basic QA in README.md

### PR DESCRIPTION
**Pull request by kishore-narendran**

### CODE REVIEW

**Comment by sigit-prayoga** [comment]
Done

**Comment by mhaidarhanif** [comment]
@kishore-narendran Thank you for migrating the other data from the spreasheet.
@sigit-prayoga Alright.

Maybe I will edit some minor editing style. Because in Markdown, there is a code syntax like branch not just -branch. I actually have updated them in the newer version of our spreadsheet, but not the public copy yet.

**Comment by mhaidarhanif** [comment]
Almost forgot. Should we omit the Duration?

**Comment by mhaidarhanif** [comment]
Okay, we should omit them. I actually planned to edit them tonight, but I should have a rest right now.

**Pull request merged**
